import sqlalchemy

Trial_mode = True


dbConfig = {
    'host': '127.0.0.1',
    'user': 'mgnl',
    'password': 'password',
    'database': ('py_sql_test' if Trial_mode else 'py_sql'),
    'port': 3306,
}


db_field_types = {
    'yahoofinance_stock_balance_sheet': {
        'Code': sqlalchemy.types.String(length=50),
        'ReportDate': sqlalchemy.types.Date,
        'CashAndCashEquivalents': sqlalchemy.types.Float,
        'OtherShortTermInvestments': sqlalchemy.types.Float,
        'CashCashEquivalentsAndShortTermInvestments': sqlalchemy.types.Float,
        'AccountsReceivable': sqlalchemy.types.Float,
        'Inventory': sqlalchemy.types.Float,
        'OtherCurrentAssets': sqlalchemy.types.Float,
        'CurrentAssets': sqlalchemy.types.Float,
        'GrossPPE': sqlalchemy.types.Float,
        'AccumulatedDepreciation': sqlalchemy.types.Float,
        'NetPPE': sqlalchemy.types.Float,
        'InvestmentsAndAdvances': sqlalchemy.types.Float,
        'Goodwill': sqlalchemy.types.Float,
        'OtherIntangibleAssets': sqlalchemy.types.Float,
        'OtherNonCurrentAssets': sqlalchemy.types.Float,
        'TotalNonCurrentAssets': sqlalchemy.types.Float,
        'TotalAssets': sqlalchemy.types.Float,
        'CurrentDebt': sqlalchemy.types.Float,
        'AccountsPayable': sqlalchemy.types.Float,
        'IncomeTaxPayable': sqlalchemy.types.Float,
        'CurrentAccruedExpenses': sqlalchemy.types.Float,
        'CurrentDeferredRevenue': sqlalchemy.types.Float,
        'OtherCurrentLiabilities': sqlalchemy.types.Float,
        'CurrentLiabilities': sqlalchemy.types.Float,
        'LongTermDebt': sqlalchemy.types.Float,
        'NonCurrentDeferredTaxesLiabilities': sqlalchemy.types.Float,
        'NonCurrentDeferredRevenue': sqlalchemy.types.Float,
        'OtherNonCurrentLiabilities': sqlalchemy.types.Float,
        'TotalNonCurrentLiabilitiesNetMinorityInterest': sqlalchemy.types.Float,
        'TotalLiabilitiesNetMinorityInterest': sqlalchemy.types.Float,
        'CapitalStock': sqlalchemy.types.Float,
        'RetainedEarnings': sqlalchemy.types.Float,
        'GainsLossesNotAffectingRetainedEarnings': sqlalchemy.types.Float,
        'StockholdersEquity': sqlalchemy.types.Float,
    },
    'yahoofinance_stock_income_statement': {
        'ReportDate': sqlalchemy.types.Date,
        'Code': sqlalchemy.types.String(length=50),
        'ValuationMethod': sqlalchemy.types.String(length=50),
        'TotalRevenue': sqlalchemy.types.Float,
        'CostOfRevenue': sqlalchemy.types.Float,
        'GrossProfit': sqlalchemy.types.Float,
        'OperatingExpense': sqlalchemy.types.Float,
        'ResearchAndDevelopment': sqlalchemy.types.Float,
        'SellingGeneralAndAdministration': sqlalchemy.types.Float,
        'OperatingExpense"': sqlalchemy.types.Float,
        'OperatingIncome': sqlalchemy.types.Float,
        'InterestExpense': sqlalchemy.types.Float,
        'OtherIncomeExpense': sqlalchemy.types.Float,
        'PretaxIncome': sqlalchemy.types.Float,
        'TaxProvision': sqlalchemy.types.Float,
        'NetIncomeContinuousOperations': sqlalchemy.types.Float,
        'NetIncome': sqlalchemy.types.Float,
        'NetIncomeCommonStockholders': sqlalchemy.types.Float,
        'BasicEPS': sqlalchemy.types.Float,
        'DilutedEPS': sqlalchemy.types.Float,
        'BasicAverageShares': sqlalchemy.types.Float,
        'DilutedAverageShares': sqlalchemy.types.Float,
        'Ebitda': sqlalchemy.types.Float,
    },
    'yahoofinance_stock_price': {
        'Code': sqlalchemy.types.String(length=50),
        'Date': sqlalchemy.types.Date,
        'Open': sqlalchemy.types.Float,
        'High': sqlalchemy.types.Float,
        'Low': sqlalchemy.types.Float,
        'Close': sqlalchemy.types.Float,
        'Adj Close': sqlalchemy.types.Float,
        'Volume': sqlalchemy.types.Float,
    },
    'yahoofinance_stock_valuation_measures': {
        'Code': sqlalchemy.types.String(length=50),
        'ValuationMethod': sqlalchemy.types.String(length=50),
        'ReportDate': sqlalchemy.types.Date,
        'MarketCap': sqlalchemy.types.Float,
        'EnterpriseValue': sqlalchemy.types.Float,
        'PeRatio': sqlalchemy.types.Float,
        'ForwardPeRatio': sqlalchemy.types.Float,
        'PegRatio': sqlalchemy.types.Float,
        'PsRatio': sqlalchemy.types.Float,
        'PbRatio': sqlalchemy.types.Float,
        'EnterprisesValueRevenueRatio': sqlalchemy.types.Float,
        'EnterprisesValueEBITDARatio': sqlalchemy.types.Float,
    },
}
